INSERT INTO `movies` (name, duration, genre, `year`) VALUES ('The Shawshank Redemption', 120, 'Crime', '1994-02-01'),
                                                            ('The Silence of the Lambs', 130, 'Crime', '1991-01-05'),
                                                            ('Chocolat', 115, 'Drama', '2000-05-03'),
                                                            ('Titanic', 125, 'Drama', '1997-06-06'),
                                                            ('The Terminal', 135, 'Drama', '2004-08-25'),
                                                            ('Braveheart (1995)', 140, 'War', '1995-12-10'),
                                                            ('A Dame to Kill For', 155, 'Action', '2014-11-09'),
                                                            ('Live and Let Die', 150, 'Action', '1973-09-30'),
                                                            ('Men in Black', 160, 'Comedy', '1997-06-03'),
                                                            ('Shrek', 123, 'Comedy', '2001-05-25'),
                                                            ('The English Patient', 121, 'War', '1996-10-10'),
                                                            ('The Last Samurai', 119, 'War', '2003-03-19'),
                                                            ('The Pianist', 90, 'War', '2002-02-03'),
                                                            ('The Bodyguard', 100, 'Thriller', '1992-09-22'),
                                                            ('Pulp Fiction', 105, 'Thriller', '1994-10-25'),
                                                            ('Basic Instinct', 124, 'Thriller', '1992-03-26'),
                                                            ('Gattaca', 103, 'Thriller', '1997-04-24'),
                                                            ('Open Water', 104, 'Horror', '2003-03-28'),
                                                            ('Frenzy', 115, 'Horror', '1972-12-31'),
                                                            ('28 Weeks Later', 120, 'Horror', '2007-07-27');

INSERT INTO `rooms` (seats) VALUES (20),
                                   (25),
                                   (30),
                                   (40),
                                   (35),
                                   (50),
                                   (55),
                                   (60),
                                   (20),
                                   (20),
                                   (30),
                                   (30),
                                   (35),
                                   (40),
                                   (50),
                                   (55),
                                   (60),
                                   (35),
                                   (40),
                                   (35);