spring:
  application:
    name: cinema
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mariadb://localhost:3306/cinema
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mypass}
    driverClassName: org.mariadb.jdbc.Driver