spring:
  application:
    name: cinema
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mariadb://localhost:3306/cinema
    username: root
    password: hui$E111
    driverClassName: org.mariadb.jdbc.Driver
